version: "3"
services:
    # mesh_yggdrasil:
    #     container_name: mesh_yggdrasil
    #     image: luzifer/yggdrasil:v0.3.11
    #     network_mode: host
    #     cap_add:
    #         - NET_ADMIN
    #     devices:
    #         - "/dev/net/tun:/dev/net/tun"
    #     volumes:
    #         - ./data/yggdrasil_data:/config

    # mesh_cjdns:
    #     container_name: mesh_cjdns
    #     image: chpio/cjdns:latest
    #     network_mode: host
    #     cap_add:
    #         - NET_ADMIN
    #     volumes:
    #         - ./data/cjdns_data:/data/cjdns
    #     devices:
    #         - "/dev/net/tun:/dev/net/tun"

    # mesh_ssb-server:
    #     container_name: mesh_ssb-server
    #     image: distributedmind/ssb-server:latest
    #     environment:
    #         - DOMAIN=example.org
    #     ports:
    #         - "8008:8008"
    #     volumes:
    #         - ./data/ssb_data:/ssb/.ssb

    mesh_ipfs:
        container_name: mesh_ipfs
        image: ipfs/go-ipfs:v0.4.22
        volumes:
            - ./data/ipfs_staging:/export
            - ./data/ipfs_data:/data/ipfs
        ports:
            - "4001:4001"
            - "127.0.0.1:8080:8080"
            # For public gateway:
            #- "8080:8080"
            - "127.0.0.1:5001:5001"

    mesh_node:
        container_name: mesh_node
        build: ./dockerfiles/mesh_node
        tty: true
